### ISSUE TITLE
请问支持下个给定链接下的指定文件夹吗？

### ISSUE THREAD

**Issue by lilqz66** [chenyifanthu/THU-Cloud-Downloader#3]
比如我只想下

给定链接（https://cloud.tsinghua.edu.cn/d/674208019e314311ab5c/）
下的chatglm2-6b-int4文件夹内的内容

**Comment by wangrun20** [comment]
用正则表达式

**Comment by wangrun20** [comment]
不好意思，之前的代码不支持下载给定链接下的指定文件夹，因为它的正则表达式匹配的是文件名，不匹配路径
我修改了一下代码，以便于能进行路径匹配，你可以查看最新commit的代码
你可以运行：
python thu_cloud_download.py 
    -l https://cloud.tsinghua.edu.cn/d/1234567890/ 
    -s "~/path_to_save" 
    -f "*/chatglm2-6b-int4/*"
来实现给定链接下的chatglm2-6b-int4文件夹内的内容
